---
abstract: 'Find a minimum required version of perl for Perl code'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-MinimumVersion-Fast
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Perl::MinimumVersion::Fast:
    file: lib/Perl/MinimumVersion/Fast.pm
    version: 0.09
requires:
  Compiler::Lexer: 0.11
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/Perl-MinimumVersion-Fast/issues
  homepage: https://github.com/tokuhirom/Perl-MinimumVersion-Fast
  repository: git://github.com/tokuhirom/Perl-MinimumVersion-Fast.git
version: 0.09
x_contributors:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
