---
abstract: 'Find a minimum required version of perl for Perl code'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-MinimumVersion-Fast
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Perl::MinimumVersion::Fast:
    file: lib/Perl/MinimumVersion/Fast.pm
    version: '0.15'
requires:
  Compiler::Lexer: '0.17'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/tokuhirom/Perl-MinimumVersion-Fast/issues
  homepage: https://github.com/tokuhirom/Perl-MinimumVersion-Fast
  repository: git://github.com/tokuhirom/Perl-MinimumVersion-Fast
version: '0.15'
x_contributors:
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
